import Link from "next/link";
import { notFound } from "next/navigation";

import { GameAIReviewAction } from "@/components/game-ai-review-action";
import { GameReviewWorkspace } from "@/components/game-review-workspace";
import { ResultPill } from "@/components/result-pill";
import { buildGameInsights } from "@/lib/services/game-insights";
import { getGameDetail } from "@/lib/services/repository";

export const dynamic = "force-dynamic";

function formatGameTime(value?: string | null) {
  if (!value) {
    return "Unknown time";
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return parsed.toLocaleString([], {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  });
}

export default async function GamePage(props: {
  params: Promise<{ id: string }>;
  searchParams?: Promise<{ ply?: string }>;
}) {
  const params = await props.params;
  const searchParams = props.searchParams ? await props.searchParams : undefined;
  const detail = await getGameDetail(params.id);

  if (!detail) {
    notFound();
  }
  const insights = buildGameInsights(detail);
  const plyCandidate = searchParams?.ply ? Number.parseInt(searchParams.ply, 10) : NaN;
  const selectedPly = Number.isFinite(plyCandidate) ? plyCandidate : undefined;
  const criticalMomentNotesByPly = new Map(detail.criticalMomentNotes.map((note) => [note.ply, note]));
  const criticalMoments = detail.engineReviews.map((review) => ({
    ply: review.ply,
    label: review.label,
    deltaCp: review.deltaCp,
    whatHappened: criticalMomentNotesByPly.get(review.ply)?.whatHappened,
    whyItMatters: criticalMomentNotesByPly.get(review.ply)?.whyItMatters,
    whatToThink: criticalMomentNotesByPly.get(review.ply)?.whatToThink,
    trainingFocus: criticalMomentNotesByPly.get(review.ply)?.trainingFocus,
    aiAvailable: criticalMomentNotesByPly.has(review.ply)
  }));

  return (
    <main className="space-y-6">
      <section className="panel space-y-4">
        <Link className="text-sm font-semibold uppercase tracking-[0.18em]" href="/">
          Back to dashboard
        </Link>
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <span className="badge">Game review</span>
            <h1 className="mt-3 font-display text-4xl">{detail.game.opening || "Imported game"}</h1>
            <div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-muted">
              <span>
                {detail.game.whitePlayer} vs {detail.game.blackPlayer}
              </span>
              <ResultPill result={detail.resultLabel} />
            </div>
            <p className="mt-1 text-xs uppercase tracking-[0.12em] text-muted">
              Imported game time: {formatGameTime(detail.game.playedAt)}
            </p>
          </div>
          <div className="surface-soft px-5 py-4 text-sm text-muted-strong">
            <p>
              {detail.review
                ? `${detail.review.coachSource === "openai" ? "AI coach" : "Engine fallback"} • ${Math.round(detail.review.confidence * 100)}% confidence`
                : "No coach narrative yet"}
            </p>
            <div className="mt-3">
              <GameAIReviewAction
                gameId={detail.game.id}
                hasAIReview={detail.review?.coachSource === "openai"}
                analysisStatus={detail.game.analysisStatus}
              />
            </div>
          </div>
        </div>

        {detail.review ? (
          <div className="grid gap-4 xl:grid-cols-3">
            <div className="tone-neutral p-5 xl:col-span-2">
              <h2 className="font-display text-2xl">Summary</h2>
              <p className="mt-2 text-xs uppercase tracking-[0.12em] text-muted">
                {detail.review.coachSource === "openai"
                  ? `Generated by ${detail.review.coachModel || detail.review.coachProvider || "AI"}`
                  : "Generated from engine-backed fallback coaching"}
              </p>
              <p className="mt-3 text-sm leading-6 text-muted-strong">{detail.review.summary}</p>
            </div>
            <div className="surface-card p-5">
              <h2 className="font-display text-2xl">Action items</h2>
              <ul className="mt-3 space-y-2 text-sm leading-6 text-muted">
                {detail.review.actionItems.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
        ) : (
          <p className="surface-soft p-5 text-sm text-muted-strong">Run analysis to generate a review.</p>
        )}

        <article className="tone-info p-5">
          <h2 className="font-display text-2xl">Leaks analyzed in this game</h2>
          {insights.analyzedLeaks.length ? (
            <div className="mt-4 grid gap-3 md:grid-cols-2">
              {insights.analyzedLeaks.map((leak) => (
                <div key={leak.key} className="surface-card rounded-[18px] p-4">
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-semibold">{leak.label}</p>
                    <span className="rounded-full bg-blue-500/12 px-3 py-1 text-xs font-semibold text-[color:var(--info-text)]">
                      {leak.count} hits
                    </span>
                  </div>
                  <p className="mt-2 text-sm text-muted-strong">{leak.focus}</p>
                  <Link
                    className="btn-primary mt-3 px-3 py-2 text-xs uppercase tracking-[0.12em]"
                    href={`/leaks/${leak.key}`}
                  >
                    Open leak guide
                  </Link>
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-3 text-sm text-muted-strong">No leak categories were detected for this game yet.</p>
          )}
        </article>

        <div className="grid gap-4 xl:grid-cols-2">
          <article className="tone-danger p-5">
            <h2 className="font-display text-2xl">Where it went wrong</h2>
            <div className="mt-3 space-y-3 text-sm leading-6 text-muted-strong">
              {insights.wentWrong.map((item) => (
                <div key={item.title + item.detail}>
                  <p className="font-semibold">{item.title}</p>
                  {item.ply ? (
                    <Link
                      className="inline-block underline-offset-2 hover:underline"
                      href={`/games/${params.id}?ply=${item.ply}#replay`}
                    >
                      {item.detail} (jump to move)
                    </Link>
                  ) : (
                    <p>{item.detail}</p>
                  )}
                </div>
              ))}
            </div>
          </article>

          <article className="tone-success p-5">
            <h2 className="font-display text-2xl">Where it went right</h2>
            <ul className="mt-3 space-y-2 text-sm leading-6 text-muted-strong">
              {insights.wentRight.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </article>
        </div>

        <div className="grid gap-4 xl:grid-cols-2">
          <article className="tone-neutral p-5">
            <h2 className="font-display text-2xl">What to think next</h2>
            <ul className="mt-3 space-y-2 text-sm leading-6 text-muted-strong">
              {insights.nextThink.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </article>

          <article className="tone-info p-5">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h2 className="font-display text-2xl">Anything else</h2>
              {insights.primaryLeakKey ? (
                <Link
                  className="btn-primary px-4 py-2 text-xs uppercase tracking-[0.12em]"
                  href={`/leaks/${insights.primaryLeakKey}`}
                >
                  Focus this leak
                </Link>
              ) : null}
            </div>
            <ul className="mt-3 space-y-2 text-sm leading-6 text-muted-strong">
              {insights.extraIdeas.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </article>
        </div>
      </section>

      <section className="panel" id="replay">
        <div className="mb-6">
          <span className="badge">Replay</span>
          <h2 className="panel-title mt-3">Move-by-move board review</h2>
        </div>
        <GameReviewWorkspace
          gameId={detail.game.id}
          moves={detail.positions}
          criticalMoments={criticalMoments}
          initialPly={selectedPly}
          orientation={detail.playerColor === "black" ? "black" : "white"}
          playerColor={detail.playerColor === "black" || detail.playerColor === "white" ? detail.playerColor : undefined}
          initialMessages={detail.coachChatMessages.map((message) => ({
            id: message.id,
            role: message.role,
            content: message.content,
            focusPly: message.focusPly
          }))}
        />
      </section>
    </main>
  );
}
